import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from "@/features/users/authContext";
import { SubscriptionProvider } from "@/features/subscriptions/subscriptionContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full bg-gray-100">
      <body className="h-full">
        <AuthProvider>
          <SubscriptionProvider>
            <div className="w-full h-screen flex flex-col min-h-full">
              {children}
            </div>
          </SubscriptionProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
